### ISSUE TITLE
HEAD requests are routed to GET method

### ISSUE THREAD

**Issue by t-katsumura** [aileron-gateway/aileron-gateway#33]
### What happened?

`HEAD /liveness` requests are routed to `GET /liveness`
when the HealthCheckHandler is configured as follows.

```yaml
apiVersion: app/v1
kind: HealthCheckHandler
spec:
  patterns: ["/liveness"]
  timeout: 30
  methods:
    - GET
    - POST
```

### What did you expect to happen?

404 not found is returned to `HEAD /liveness`.

### How can we reproduce it (as minimally and precisely as possible)?

Use HealthCheckHandler with the following config.

Send a request like `curl -XHEAD http://localhost:8080/liveness`.

```yaml
apiVersion: app/v1
kind: HealthCheckHandler
spec:
  patterns: ["/liveness"]
  timeout: 30
  methods:
    - GET
    - POST
 ```

### AILERON Gateway version

```console
 $ aileron --version
# paste output here
```

<details>

```console
 $ aileron --info
# paste output here
```

</details>
